spring.application.name=energym-reservas

#servidor
server.port=8080

# H2
spring.datasource.url=jdbc:mysql://localhost:3306/energym_db?serverTimezone=UTC
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=DrkLion869@57

#JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.sql.init.mode=never
spring.jpa.defer-datasource-initialization=false

# Deshabilitar cache de Swagger
spring.web.resources.cache.period=0
springdoc.cache.disabled=true

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

